### ISSUE TITLE
update to CC license v4 instead of v3

### ISSUE THREAD

**Issue by wolftune** [figure002/getgnulinux#20]
CC BY SA 4.0 International is updated and better license, and v3 allows the update already

**Comment by s8321414** [comment]
Agree!
And @figure002 , your blog is down, right?

**Comment by figure002** [comment]
Thanks, I'll update it soon.
@s8321414 I made a mistake in the DNS records, should be fixed in a few minutes. Thanks for pointing that out!

**Comment by s8321414** [comment]
\o/ It's back online now :smile:
