### ISSUE TITLE
link to fixubuntu until UNity 8 is default

### ISSUE THREAD

**Issue by wolftune** [figure002/getgnulinux#21]
Until we see unity 8 as default, should link to http://fixubuntu.com/ when recommending Ubuntu

**Comment by figure002** [comment]
Excuse my late reply and thank you for bringing this to my attention. Looks like we don't have to wait for Unity 8; the "Include online search results" option is disabled by default in the latest Ubuntu. Closing this ticket.

**Comment by wolftune** [comment]
Indeed, and thanks for clarifying. Cheers

**Comment by Ruutger** [comment]
Hey Serrano,

Ik ben afgelopen tijd met andere dingen bezig geweest.


Ga kijken of er een ticket bij zit die ik op kan lossen,. mijn php kennis
is (nog) beperkt


Jeffrey,, de andere linux man, is er ok niet mee bezig. Waarom weet ik
niet, maar vidn denk ik toepassen in praktijk nog lastig.


Groet,

Rutger

2016-05-15 1:03 GMT+02:00 Serrano Pereira <notifications@github.com>:

> Closed #21 <https://github.com/figure002/getgnulinux/issues/21>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/figure002/getgnulinux/issues/21#event-660838427>
>



-- 
Met vriendelijke groet,

Rutger Touburg
email: rtouburg@gmail.com
tel: 06-
