### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by alisvlouis** [figure002/getgnulinux#23]
[http://getgnulinux.org/zh/switch_to_linux/choose_a_distribution/](http://getgnulinux.org/zh/switch_to_linux/choose_a_distribution/)
> <p>然而你不应该把 Linux 想成是 Windows 的克隆。想知道使用它有什么值得期待，建议你阅读我们的<a href="http://getgnulinux.org/zh/switch_to_linux/choose_a_distribution/%s">转向</a>一页。</p>

Hyperlink here is dead.

**Comment by alisvlouis** [comment]
No it is OK.

**Comment by figure002** [comment]
The link is still broken. This should be fixed in the translation. Although the website it links to in the English version is gone, so the source text should be updated as well.
