### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by alisvlouis** [figure002/getgnulinux#25]
http://blog.getgnulinux.org/participate/translation/ is dead
which can be found in many pages:

>
```HTML
<li><a href="http://blog.getgnulinux.org/participate/translation/" title="Help us reach an audience in your language!">Translation</a></li>
```

**Comment by figure002** [comment]
Thank you for reporting this. The blog should be back online.

**Comment by Ruutger** [comment]
when i click this link, it seems not working yet.
http://blog.getgnulinux.org/participate/translation/
il take  a look into it this weekend or begin next week, perhaps i can
solve it.


Rutger



2016-04-02 14:59 GMT+02:00 Louis Victory Alis <notifications@github.com>:

> http://blog.getgnulinux.org/participate/translation/ is dead
> which can be found in many pages:
>
> - Translation <http://blog.getgnulinux.org/participate/translation/>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/figure002/getgnulinux/issues/25>
>



-- 
Met vriendelijke groet,

Rutger Touburg
email: rtouburg@gmail.com
tel: 06-

**Comment by figure002** [comment]
@Ruutger Thanks! I forgot to update the DNS records. It should be back online within an hour.
