### ISSUE TITLE
Apply the traditional Chinese translation to the site

### ISSUE THREAD

**Issue by zerng07** [figure002/getgnulinux#35]
I have updated the traditional Chinese in Transifex, and would like to promote the site to people in Taiwan.

Could you please apply the translation to the site? Thanks!

PS. if there is conflicts with Transfiex one, please use the translation from Transifex directly. (I sent a pull request last time and removed some duplicates in the header of the po file, so there might be some conficts with the one from Transifex)

**Comment by figure002** [comment]
Thanks! I just updated with the latest translations from Transifex. It's best to always translate via Transifex, otherwise you might lose some translations as they will be overwritten with translations from Transifex.

**Comment by zerng07** [comment]
Thanks.

However, I don't see the change for Chinese (Taiwan), zh_TW yet. Is it published to the site?

**Comment by figure002** [comment]
My bad, I thought I had loaded the latest changes, but I hadn't. It should be published now.
