### ISSUE TITLE
Keep consistent use GNU/Linux everywhere

### ISSUE THREAD

**Issue by ComputerNerd** [figure002/getgnulinux#6]
I was very happy to see that your website domain name include GNU before Linux and the banner also correctly uses GNU/Linux instead of just Linux. Now it is time to take it one step farther and fix the remaining parts of your website that just say Linux without GNU.

**Comment by figure002** [comment]
Was finally fixed in 1a017bd2c0fb415387a62a438b20456d1d130bb0, but won't go live until the main translations are updated.
